In [1]:
import pandas as pd

## Coletando dados do csv

In [2]:
df_vendas = pd.read_csv("dataframe_nivel_1.csv", sep=",")

## Parte 1 - Estatística básica

### Informações basicas do DataFrame

In [3]:
df_vendas.describe()

       quantidade  preco_unitario
count   50.000000       50.000000
mean     3.020000      255.520000
std      1.406835      129.388553
min      1.000000       57.000000
25%      2.000000      135.250000
50%      3.000000      267.500000
75%      4.000000      357.000000
max      5.000000      485.000000

In [4]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cliente         50 non-null     str
 1   produto         50 non-null     str
 2   cidade          50 non-null     str
 3   quantidade      50 non-null     int64
 4   preco_unitario  50 non-null     int64
dtypes: int64(2), str(3)
memory usage: 2.1 KB

### Média, Mediana e Moda

In [5]:
quant_media = df_vendas["quantidade"].mean()
print(f"Média da quantidade de compra: {quant_media}")

Média da quantidade de compra: 3.02

In [6]:
preco_mediana = df_vendas["preco_unitario"].median()
print(f"Mediana do preço unitário: {preco_mediana}")

Mediana do preço unitário: 267.5

In [7]:
prod_moda = df_vendas["produto"].mode()
print(f"moda dos produtos: {prod_moda[0]}")

moda dos produtos: Monitor

## Parte 2 - Ordenação

### Ordenação pelo preco_unitario

In [8]:
df_preco_sort = df_vendas.sort_values(by="preco_unitario", ascending=False)
df_preco_sort.head()

    cliente  produto          cidade  quantidade  preco_unitario
28   Carlos  Monitor        Salvador           3             485
16   Carlos   Webcam  Belo Horizonte           4             484
47  Eduardo  Teclado        Salvador           3             476
20      Ana  Monitor        Curitiba           3             457
37  Gabriel   Webcam        Salvador           1             446

### Compras com maior quantidade

In [9]:
df_maior_quant = df_vendas.sort_values(by="quantidade", ascending=False)
df_maior_quant.head(5)

    cliente  produto          cidade  quantidade  preco_unitario
6       Ana  Teclado        Salvador           5             210
5    Carlos    Mouse             Rio           5             396
7   Daniela   Webcam  Belo Horizonte           5             351
12   Carlos   Webcam        Curitiba           5              77
40   Carlos   Webcam  Belo Horizonte           5             307

## Parte 3 - Filtros

### Vendas na cidade de são paulo

In [10]:
df_sao_paulo = df_vendas[df_vendas["cidade"] == "São Paulo"]
df_sao_paulo.head()

     cliente  produto     cidade  quantidade  preco_unitario
8    Eduardo  Headset  São Paulo           2             420
19  Fernanda  Monitor  São Paulo           1             192
27   Eduardo  Headset  São Paulo           4              77
32       Ana    Mouse  São Paulo           4             307
33     Bruno  Monitor  São Paulo           5             372

### Venda com quantidade maior que 3

In [11]:
df_quant_maior_que_3 = df_vendas[df_vendas["quantidade"] > 3]
df_quant_maior_que_3.head(10)

     cliente  produto          cidade  quantidade  preco_unitario
5     Carlos    Mouse             Rio           5             396
6        Ana  Teclado        Salvador           5             210
7    Daniela   Webcam  Belo Horizonte           5             351
12    Carlos   Webcam        Curitiba           5              77
14    Carlos  Monitor        Salvador           4              57
15   Daniela  Monitor        Salvador           4             410
16    Carlos   Webcam  Belo Horizonte           4             484
18  Fernanda   Webcam        Curitiba           5             124
22       Ana  Headset        Curitiba           5             297
23   Eduardo  Teclado        Curitiba           4             155

### Compras de mouse ou teclado

In [12]:
df_mouse_ou_teclado = df_vendas[df_vendas["produto"].isin(["Mouse", "Teclado"])]
df_mouse_ou_teclado.head(10)

    cliente  produto          cidade  quantidade  preco_unitario
0   Eduardo  Teclado             Rio           2             294
3    Carlos    Mouse        Salvador           2             233
4    Carlos    Mouse        Salvador           3             180
5    Carlos    Mouse             Rio           5             396
6       Ana  Teclado        Salvador           5             210
10  Daniela  Teclado        Curitiba           3             208
21   Carlos  Teclado             Rio           3             242
23  Eduardo  Teclado        Curitiba           4             155
25      Ana    Mouse  Belo Horizonte           2             136
32      Ana    Mouse       São Paulo           4             307

## Parte 4 - Consultas simples

### quantas vendas tem no dataframe?

In [13]:
print(f"\nTotal de quantidade de vendas: {df_vendas.shape[0]}")

Total de quantidade de vendas: 50

### Quantos produtos exitem?

In [14]:
df_produtos = df_vendas["produto"].nunique() # ou .unique para retorna um lista dos produtos
print(f"\nProdutos diponíveis: {df_produtos}")

Produtos diponíveis: 5

### Quantas vendas foram feitas por cada cidade?

In [15]:
df_vendas_cidade = df_vendas.groupby("cidade")["quantidade"].sum()
df_vendas_cidade.head(5)

cidade
Belo Horizonte    30
Curitiba          33
Rio               23
Salvador          43
São Paulo         22
Name: quantidade, dtype: int64

## Extras

#### Criando a coluna valor_total a partir da multiplicação das colunas quantidade e preco_unitario

In [16]:
df_vendas["valor_total"] = df_vendas["quantidade"] * df_vendas["preco_unitario"]

In [17]:
df_vendas.head()

   cliente  produto    cidade  quantidade  preco_unitario  valor_total
0  Eduardo  Teclado       Rio           2             294          588
1    Bruno   Webcam  Curitiba           2             275          550
2   Carlos  Monitor  Curitiba           2             181          362
3   Carlos    Mouse  Salvador           2             233          466
4   Carlos    Mouse  Salvador           3             180          540

#### Qual cliente comprou mais? (por quantidade)

In [18]:
# Qual cliente comprou mais (por quantidade)
df_quant_por_cliente = df_vendas.groupby("cliente")["quantidade"].sum().sort_values(ascending=False)
df_quant_por_cliente.head(10)

# print(df_quant_por_cliente.idxmax()) <-- retorna so o nome do primeiro

cliente
Carlos      41
Eduardo     39
Ana         25
Bruno       18
Daniela     17
Fernanda     9
Gabriel      2
Name: quantidade, dtype: int64

Vemos que *Carlos* foi quem compro mais produtos, um total de 41.

#### Qual cidade comprou mais produtos? (por quantidade)

In [19]:
df_quant_por_cidade = df_vendas.groupby("cidade")["quantidade"].sum().sort_values(ascending=False)
df_quant_por_cidade.head(10)

cidade
Salvador          43
Curitiba          33
Belo Horizonte    30
Rio               23
São Paulo         22
Name: quantidade, dtype: int64

*Salvador* foi a cidade que mais comprou, foi um total de 43 unidades.

#### Venda Total da loja

In [20]:
df_valor_total = df_vendas["valor_total"].sum()
print(f"R${df_valor_total:,.2f}")

R$38,833.00